[View in Colaboratory](https://colab.research.google.com/github/matheus217/projeto-machine-learn/blob/master/classificacao_mlp.ipynb)

In [0]:
# Artificial Neural Network
# from https://www.superdatascience.com/machine-learning/ 

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [187]:
import os
import tarfile
from six.moves import urllib

FILE_TO_DOWNLOAD =  "data.csv"
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/willcribeiro/Autonomous-Robot/master/"
DATA_PATH = "Dados/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+file_to_download)
  
  
fetch_data()

# observando se o diretório datasets foi criado com sucesso 
!ls Dados

data.csv


In [188]:
# Importing the dataset
dataset = pd.read_csv(DATA_PATH+'data.csv')


dataset.head(  )

S0rvo0   S0rvo30   S0rvo60   S0rvo90   S0rvo120   S0rvo150   S0rvo180  \
0  59.6907   60.0000  60.00000  54.15810   10.36080   14.77660   60.00000   
1  34.5533   60.0000   8.90034   7.73196    8.52234   60.00000   60.00000   
2  35.5670   53.4192  60.00000  60.00000    9.69072   11.94160   60.00000   
3  38.6598   49.2783  60.00000  60.00000    9.29553    6.39175    9.34708   
4  39.0378   41.0309  60.00000  10.51550    7.38832    8.26460   60.00000   

    Action  
0        0  
1        1  
2        0  
3        0  
4        0

In [0]:
import numpy as np

X = dataset.iloc[:,[0,1,2,3,4,5,6]].values
y = dataset.iloc[:, 7].values

y_new = [] 

for i in range(len(y)):

  if y[i]==0:
    y_new.append([0,0,1])
    
  elif y[i]==1:
    y_new.append([0,1,0])
    
  else:
    y_new.append([1,0,0]) 
    
  


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y_new, test_size = 0.2, random_state = 0)
X_train = X_test = X
y_train = y_test = y_new
#print(X)
#print(y)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#print(X_train)
#print(X_test)

In [0]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense


# Initialising the ANN
classifier = Sequential()

In [0]:
# Adding the input layer and the first hidden layer
classifier.add(Dense( activation = 'relu', input_dim = 7, units = 14, kernel_initializer = 'uniform'))

#Adding the second hidden layer
classifier.add(Dense( activation = 'sigmoid', units = 7, kernel_initializer = 'uniform' ))

# Adding the output layer
classifier.add(Dense( activation = 'softmax', units = 3, kernel_initializer = 'uniform'))


In [0]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])


In [195]:
# Fitting the ANN to the Training set
classifier.fit(np.array(X_train),np.array(y_train), batch_size = 30, epochs = 40)


Epoch 1/40
317/317 [==============================] - 0s 2ms/step - loss: 0.2222 - acc: 0.3344
Epoch 2/40
317/317 [==============================] - 0s 59us/step - loss: 0.2211 - acc: 0.3975
Epoch 3/40
317/317 [==============================] - 0s 58us/step - loss: 0.2201 - acc: 0.3975
Epoch 4/40
317/317 [==============================] - 0s 62us/step - loss: 0.2192 - acc: 0.3975
Epoch 5/40
317/317 [==============================] - 0s 64us/step - loss: 0.2186 - acc: 0.3975
Epoch 6/40
317/317 [==============================] - 0s 66us/step - loss: 0.2179 - acc: 0.3975
Epoch 7/40
317/317 [==============================] - 0s 60us/step - loss: 0.2171 - acc: 0.3975
Epoch 8/40
317/317 [==============================] - 0s 61us/step - loss: 0.2162 - acc: 0.3975
Epoch 9/40
317/317 [==============================] - 0s 60us/step - loss: 0.2151 - acc: 0.3975
Epoch 10/40
317/317 [==============================] - 0s 58us/step - loss: 0.2135 - acc: 0.3975
Epoch 11/40
317/317 [===================

In [0]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(y_test)
#print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
y_test_non_category = [ np.argmax(t) for t in y_test ]
y_pred_non_category = [ np.argmax(t) for t in y_pred ]

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_non_category, y_pred_non_category)
#cm = confusion_matrix(y_test, y_pred)

In [197]:
from sklearn.metrics import accuracy_score
#print(y_pred)
print("Matriz de Confusão:")
print(cm)
print("Taxa de acerto:")
print(accuracy_score(y_test_non_category, y_pred_non_category))


Matriz de Confusão:
[[ 37  37   2]
 [  0  88  27]
 [  0   2 124]]
Taxa de acerto:
0.7854889589905363
